# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node.js image as the base image
FROM node:20-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json ./

# Install development dependencies
RUN npm install --ignore-scripts

# Copy the entire source directory
COPY . .

# Build the application
RUN npm run build

# Use a smaller Node.js image for the final container
FROM node:18-slim

# Set the working directory
WORKDIR /app

# Copy the built files from the builder stage
COPY --from=builder /app/dist ./dist

# Copy package.json for production dependencies
COPY --from=builder /app/package.json ./package.json

# Install only production dependencies
RUN npm ci --only=production

# Set the environment variable
ENV TODOIST_API_TOKEN=your_api_token_here


# Command to run the application
ENTRYPOINT ["node", "dist/index.js"]
